# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trougao.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrougao.proto\"\x1d\n\x05Tacka\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"B\n\x07Trougao\x12\x11\n\x01\x41\x18\x01 \x01(\x0b\x32\x06.Tacka\x12\x11\n\x01\x42\x18\x02 \x01(\x0b\x32\x06.Tacka\x12\x11\n\x01\x43\x18\x03 \x01(\x0b\x32\x06.Tacka\"2\n\x10ParametriTrougla\x12\x0c\n\x04obim\x18\x01 \x01(\x02\x12\x10\n\x08povrsina\x18\x02 \x01(\x02\x32\x45\n\x10RacunanjeTrougla\x12\x31\n\x10IzracunajTrougao\x12\x08.Trougao\x1a\x11.ParametriTrougla\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trougao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TACKA']._serialized_start=17
  _globals['_TACKA']._serialized_end=46
  _globals['_TROUGAO']._serialized_start=48
  _globals['_TROUGAO']._serialized_end=114
  _globals['_PARAMETRITROUGLA']._serialized_start=116
  _globals['_PARAMETRITROUGLA']._serialized_end=166
  _globals['_RACUNANJETROUGLA']._serialized_start=168
  _globals['_RACUNANJETROUGLA']._serialized_end=237
# @@protoc_insertion_point(module_scope)
